#!/bin/bash

rm -rvf build/enrouteManualAssets
mkdir -p build/enrouteManualAssets
cd build/enrouteManualAssets

#
# Generate waypoint icons
#
echo "Generating waypoint icons..."
mkdir waypointIcons
rsvg-convert ../../src/flightMap/sprites/AD.svg -o waypointIcons/AD.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/AD-GLD.svg -o waypointIcons/AD-GLD.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/AD-GRASS.svg -o waypointIcons/AD-GRASS.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/AD-INOP.svg -o waypointIcons/AD-INOP.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/AD-MIL.svg -o waypointIcons/AD-MIL.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/AD-MIL-GRASS.svg -o waypointIcons/AD-MIL-GRASS.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/AD-MIL-PAVED.svg -o waypointIcons/AD-MIL-PAVED.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/AD-PAVED.svg -o waypointIcons/AD-PAVED.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/AD-UL.svg -o waypointIcons/AD-UL.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/AD-WATER.svg -o waypointIcons/AD-WATER.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/MRP.svg -o waypointIcons/MRP.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/NDB.svg -o waypointIcons/NDB.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/RP.svg -o waypointIcons/RP.png -h 30 -w 30
rsvg-convert ../../src/flightMap/sprites/VOR.svg -o waypointIcons/VOR.png -w 30
rsvg-convert ../../src/flightMap/sprites/VOR.svg -o waypointIcons/DVOR.png -w 30
rsvg-convert ../../src/flightMap/sprites/VORDME.svg -o waypointIcons/VOR-DME.png -w 30
rsvg-convert ../../src/flightMap/sprites/VORDME.svg -o waypointIcons/DVOR-DME.png -w 30
rsvg-convert ../../src/flightMap/sprites/VORTAC.svg -o waypointIcons/VORTAC.png -w 30
rsvg-convert ../../src/flightMap/sprites/VORTAC.svg -o waypointIcons/DVORTAC.png -w 30
rsvg-convert ../../src/icons/waypoints/ic_warning_18px.svg -o waypointIcons/NOTAM.png -w 30
rsvg-convert ../../src/icons/waypoints/WP-map.svg -o waypointIcons/WP.png -w 10
#mv *.png ../../3rdParty/enrouteManual/05-referencePages
exit 0

#
#  COMMAND pwd
#  COMMAND python3 ${CMAKE_CURRENT_SOURCE_DIR}/generateAttributions.py

#
# Screenshots
#

QT_QPA_PLATFORM=xcb LC_ALL=en_US ${CMAKE_BINARY_DIR}/src/enroute --sm
#mv 01-*.png ../../3rdParty/enrouteManual/01-gettingStarted/autogenerated/
#mv 02-*.png ../../3rdParty/enrouteManual/02-tutorialBasic/autogenerated/
#mv 03-*.png ../../3rdParty/enrouteManual/03-tutorialAdvanced/autogenerated/
#mv 05-*.png ../../3rdParty/enrouteManual/05-referencePages/autogenerated/

#
# Manual texts
#

echo "Privacy Policies" >../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "================" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "English" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "-------" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
QT_QPA_PLATFORM=xcb LC_ALL=EN ${CMAKE_BINARY_DIR}/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
    #
echo "Deutsche Übersetzung" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "--------------------" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
QT_QPA_PLATFORM=xcb LC_ALL=DE ${CMAKE_BINARY_DIR}/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
    #
echo "Traduction en français" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "----------------------" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
QT_QPA_PLATFORM=xcb LC_ALL=FR ${CMAKE_BINARY_DIR}/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
    #
echo "Traduzione italiana" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "-------------------" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
QT_QPA_PLATFORM=xcb LC_ALL=IT ${CMAKE_BINARY_DIR}/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
    #
echo "Polskie tłumaczenie" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "-------------------" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
QT_QPA_PLATFORM=xcb LC_ALL=PL ${CMAKE_BINARY_DIR}/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
    #
echo "Traducción al español" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "---------------------" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
QT_QPA_PLATFORM=xcb LC_ALL=ES ${CMAKE_BINARY_DIR}/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
echo "" >>../../3rdParty/enrouteManual/08-appendix/03-privacy.rst
    #
echo "Authors" >../../3rdParty/enrouteManual/08-appendix/04-authors.rst
echo "=======" >>../../3rdParty/enrouteManual/08-appendix/04-authors.rst
QT_QPA_PLATFORM=xcb LC_ALL=EN ${CMAKE_BINARY_DIR}/src/enroute --string :text/authors.html | pandoc --from=HTML --write=rst >>../../3rdParty/enrouteManual/08-appendix/04-authors.rst
    #
    COMMENT "Generate texts for manual"
    DEPENDS ${PROJECT_NAME}
  )

