/***************************************************************************
 *   Copyright (C) 2021 by Stefan Kebekus                                  *
 *   stefan.kebekus@gmail.com                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

#pragma once

#include <QGeoPositionInfo>
#include <QTimer>

#include "units/Distance.h"
#include "units/Speed.h"

class DemoRunner;

namespace Traffic {

/*! \brief Traffic opponents
 *
 *  Objects of this class represent traffic opponents, as detected by FLARM and
 *  similar devices.  Instances of this class will be generated by the
 *  Navigation::FLARMAdaptor class. Consumers of this class will never have to
 *  set or construct instances of the class themselves
 */

class TrafficFactor_Abstract : public QObject {
    Q_OBJECT

    // Only friends can set properties
    friend class ::DemoRunner;
    friend class TrafficDataProvider;
    friend class TrafficDataSource_Abstract;

public:
    /*! \brief Aircraft type */
    enum AircraftType
    {
        unknown, /*!< Unknown aircraft type */
        Aircraft, /*!< Fixed wing aircraft */
        Airship, /*!< Airship, such as a zeppelin or a blimp */
        Balloon, /*!< Balloon */
        Copter, /*!< Helicopter, gyrocopter or rotorcraft */
        Drone, /*!< Drone */
        Glider, /*!< Glider, including powered gliders and touring motor gliders */
        HangGlider, /*!< Hang glider */
        Jet, /*!< Jet aircraft */
        Paraglider, /*!< Paraglider */
        Skydiver, /*!< Skydiver */
        StaticObstacle, /*!< Static obstacle */
        TowPlane /*!< Tow plane */
    };
    Q_ENUM(AircraftType)

    /*! \brief Default constructor
     *
     * @param parent The standard QObject parent pointer
     */
    explicit TrafficFactor_Abstract(QObject *parent = nullptr);

    // Standard destructor
    ~TrafficFactor_Abstract() override = default;

    //
    // Methods
    //

    /*! \brief Updates the timestamp to the current time, extending the life time of the object */
    virtual void updateTimestamp() = 0;


    //
    // PROPERTIES
    //

    /*! \brief Alarm Level, as reported by FLARM
     *
     * This is the alarm level associated with the traffic object. Alarm levels
     * are not computed by this class, but by the FLARM device that reports the
     * traffic. This is an integer in the range 0, …, 3 with the following
     * meaning.
     *
     *  - 0 = no alarm (also used for no-alarm traffic information)
     *  - 1 = alarm, 13-18 seconds to impact
     *  - 2 = alarm, 9-12 seconds to impact
     *  - 3 = alarm, 0-8 seconds to impact
     */
    Q_PROPERTY(int alarmLevel READ alarmLevel WRITE setAlarmLevel NOTIFY alarmLevelChanged)

    /*! \brief Getter method for property with the same name
     *
     *  @returns Property alarmLevel
     */
    int alarmLevel() const
    {
        return _alarmLevel;
    }

#warning
    void setAlarmLevel(int newAlarmLevel) {
        if (_alarmLevel == newAlarmLevel) {
            return;
        }
        if ((newAlarmLevel < 0) || (newAlarmLevel > 3)) {
            return;
        }
        _alarmLevel = newAlarmLevel;
        emit alarmLevelChanged();
    }

    /*! \brief Indicates if changes in properties should be animated in the GUI
     *
     *  This method indicates if changes in properties should be animated in the
     *  GUI. It is "true" if the class believes that changes in the properties
     *  indicate movement of the traffic opponent. It is "false" if the class
     *  believes that changes in the properties indicate that a new traffic
     *  opponent is being tracked.
     */
    Q_PROPERTY(bool animate READ animate WRITE setAnimate NOTIFY animateChanged)

    /*! \brief Getter method for property with the same name
     *
     *  @returns Property animate
     */
    bool animate() const
    {
        return _animate;
    }

#warning
    void setAnimate(bool newAnimate) {
        if (_animate == newAnimate) {
            return;
        }
        _animate = newAnimate;
        emit animateChanged();
    }

    /*! \brief Call sign
     *
     *  If known, this property holds the call sign of the traffic.  Otherwise, it contains an empty string
     */
    Q_PROPERTY(QString callSign READ callSign WRITE setCallSign NOTIFY callSignChanged)

    /*! \brief Getter method for property with the same name
     *
     *  @returns Property climbRate
     */
    QString callSign() const
    {
        return m_callSign;
    }

#warning
    void setCallSign(const QString& newCallsign) {
        if (m_callSign == newCallsign) {
            return;
        }
        m_callSign = newCallsign;
        emit callSignChanged();
    }

    /*! \brief Suggested color for GUI representation of the traffic
     *
     *  This propery suggests a color, depending on the alarmLevel.
     *
     *  - alarmLevel == 0: green
     *  - alarmLevel == 1: yellow
     *  - alarmLevel >= 2: red
     */
    Q_PROPERTY(QString color READ color NOTIFY alarmLevelChanged)

    /*! \brief Getter method for property with the same name
     *
     *  @returns Property color
     */
    QString color() const
    {
        if (_alarmLevel == 0) {
            return "green";
        }
        if (_alarmLevel == 1) {
            return "yellow";
        }
        return "red";
    }

    /*! \brief Description of the traffic, for use in GUI
     *
     *  This method holds a human-readable, translated description of the
     *  traffic. This is a rich-text string of the form "Glider<br>+15 0m" or
     *  "Airship<br>Position unknown<br>-45 ft".
     */
    Q_PROPERTY(QString description READ description NOTIFY descriptionChanged)

    /*! \brief Getter method for property with the same name
     *
     *  @returns Property description
     */
    QString description() const
    {
        return _description;
    }

    /*! \brief Identifier string of the traffic
     *
     *  This property holds an identifier string for the traffic, as assigned by
     *  the FLARM device that reported the traffic. This can be the FLARM ID, or
     *  an empty string if no meaningful ID can be assigned.
     */
    Q_PROPERTY(QString ID READ ID WRITE setID NOTIFY IDChanged)

    /*! \brief Getter method for property with the same name
     *
     *  @returns Property ID
     */
    QString ID() const
    {
        return _ID;
    }

#warning
    void setID(const QString& newID) {
        if (_ID == newID) {
            return;
        }
        _ID = newID;
        emit IDChanged();
    }

    /*! \brief Type of aircraft, as reported by FLARM */
    Q_PROPERTY(AircraftType type READ type WRITE setType NOTIFY typeChanged)

    /*! \brief Getter method for property with the same name
     *
     *  @returns Property vDist
     */
    AircraftType type() const
    {
        return _type;
    }

#warning
    void setType(AircraftType newType) {
        if (_type == newType) {
            return;
        }
        _type = newType;
        emit typeChanged();
    }

    /*! \brief Validity
     *
     * A traffic object is considered valid if the data is meaningful and if the
     * report is no older than the time specified in timeoutMS.  Only valid
     * traffic objects should be shown in the GUI.
     */
    Q_PROPERTY(bool valid READ valid NOTIFY validChanged)

    /*! \brief Getter method for property with the same name
     *
     *  @returns Property valid
     */
    bool valid() const
    {
        return _valid;
    }

    /*! \brief Vertical distance from own position to the traffic, at the time
     *  of report
     *
     *  If known, this property holds the vertical distance from the own
     *  position to the traffic, at the time of report.  Otherwise, it contains
     *  NaN.
     */
    Q_PROPERTY(AviationUnits::Distance vDist READ vDist WRITE setVDist NOTIFY vDistChanged)

    /*! \brief Getter method for property with the same name
     *
     *  @returns Property vDist
     */
    AviationUnits::Distance vDist() const
    {
        return _vDist;
    }

#warning
    void setVDist(AviationUnits::Distance newVDist) {
        if (_vDist == newVDist) {
            return;
        }
        _vDist = newVDist;
        emit vDistChanged();
    }

signals:
    /*! \brief Notifier signal */
    void alarmLevelChanged();

    /*! \brief Notifier signal */
    void animateChanged();

    /*! \brief Notifier signal */
    void callSignChanged();

    /*! \brief Notifier signal */
    void colorChanged();

    /*! \brief Notifier signal */
    void descriptionChanged();

    /*! \brief Notifier signal */
    void IDChanged();

    /*! \brief Notifier signal */
    void typeChanged();

    /*! \brief Notifier signal */
    void vDistChanged();

    /*! \brief Notifier signal */
    void validChanged();

private slots:
    // Setter function for the property color. This slot is bound to the
    // notifier signals of all the properties that color depends on.
    void setColor();

    // Setter function for the property description. This slot is bound to the
    // notifier signals of all the properties that color depends on.
    virtual void setDescription() = 0;

    // Setter function for the property valid. This slot is bound to the
    // notifier signals of all the properties that color depends on.  This
    // method will also set the timer, to ensure that it is called again once
    // the object times out.
    virtual void setValid() = 0;

private:
    // Copy data from other object
    void copyFrom(const TrafficFactor_Abstract & other)
    {
        setAlarmLevel(other.alarmLevel());
        setAnimate(other.animate());
        setCallSign(other.callSign());
        setID(other.ID());
        setType(other.type());
        setVDist(other.vDist());
    }

    // Set data
    void setData(int newAlarmLevel,
                 const QString & newID,
                 AviationUnits::Distance newVDist,
                 AircraftType newType,
                 const QString & newCallSign);

private:
    //
    // Property values
    //
    int _alarmLevel {0};
    bool _animate {true};
    QString m_callSign {};
    QString _color {QStringLiteral("red")};
    QString _description;
    QString _ID;
    AircraftType _type {AircraftType::unknown};
    AviationUnits::Distance _vDist;
    bool _valid {false};

    // Timer for timeout. Traffic objects become invalid if their data has not been
    // refreshed for timeoutMS milliseconds
    QTimer timeoutCounter;
    static constexpr qint64 timeoutMS = 10*1000;
};

}
