name: enroute-flight-navigation # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
adopt-info: enroute
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0

apps:
  enroute:
    command: usr/bin/enroute
    common-id: de.akaflieg_freiburg.enroute
    desktop: usr/share/applications/de.akaflieg_freiburg.enroute.desktop
    extensions:
      - kde-neon
    plugs:
      - kde-frameworks-5-plug
      - desktop
      - network
      - network-bind
      - opengl
      - process-control
      - wayland
      - x11      

parts:
  enroute:
    parse-info:
      - usr/share/metainfo/de.akaflieg_freiburg.enroute.appdata.xml
    plugin: cmake
    source: .
    build-snaps:
      - kde-frameworks-5-qt-5-15-core20-sdk
      - kde-frameworks-5-qt-5-15-core20
    build-packages:
      - git
      - doxygen
    stage-snaps:
      - kde-frameworks-5-qt-5-15-core20
    cmake-parameters:
      - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_TESTING=OFF"
      - "-DBUILD_TESTING=OFF"
      - "-DKDE_SKIP_TEST_SETTINGS=ON"
      - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
 