name: enroute-flight-navigation # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
adopt-info: enroute
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0

apps:
  enroute-flight-navigation:
    command: usr/bin/enroute
    common-id: de.akaflieg_freiburg.enroute
    desktop: usr/share/applications/de.akaflieg_freiburg.enroute.desktop
    extensions:
      - kde-neon
    plugs:
      - kde-frameworks-5-plug
      - desktop
      - network
      - network-bind
      - opengl
      - process-control
      - wayland
      - x11      

parts:
  enroute:
    parse-info:
      - usr/share/metainfo/de.akaflieg_freiburg.enroute.appdata.xml
    plugin: cmake
    source: .
    build-snaps:
      - kde-frameworks-5-qt-5-15-core20-sdk
    build-packages:
      - git
      - doxygen
      - libgl-dev
    cmake-parameters:
      - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_TESTING=OFF"
      - "-DBUILD_TESTING=OFF"
      - "-DKDE_SKIP_TEST_SETTINGS=ON"
      - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
    override-build: |
      snapcraftctl build
      sed -i.bak -e 's|Icon=de.akaflieg_freiburg.enroute|Icon=usr/share/icons/hicolor/scalable/apps/de.akaflieg_freiburg.enroute.svg|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/de.akaflieg_freiburg.enroute.desktop

  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  #
  # More info: https://forum.snapcraft.io/t/reducing-the-size-of-desktop-snaps/17280#heading--cleanup-part
  #
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - enroute
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - kde-frameworks-5-qt-5-15-core20-sdk
    override-prime: |
      set -eux
      for snap in "kde-frameworks-5-qt-5-15-core20-sdk"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
