name: enroute-flight-navigation # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.8' # just for humans, typically '1.2+git' or '1.3.2'
summary: A flight navigation app for VFR pilots # 79 char long summary
description: |
  Enroute Flight Navigation is a flight navigation app for VFR pilots. The
  app runs primarily on mobile devices.  It is free, open source, 100%
  non-commercial and does not collect user data.  This desktop version of the
  app is hardly useful for actual navigation, but might be used to plan your
  next flight on the big screen.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  enroute-flight-navigation:
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://github.com/Akaflieg-Freiburg/enroute.git
    build-snaps:
      - cmake
      - kde-frameworks-5-qt-5-14-core18-sdk
      - kde-frameworks-5-qt-5-14-core18
